In [11]:
       
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt   
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import warnings
warnings.filterwarnings('ignore')

In [12]:
df2=pd.read_csv(r"C:\Users\bhagy\OneDrive\Desktop\practice\50_Startups.csv")
df2.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [13]:
df2.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [14]:
df2.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [15]:
x=df2.iloc[:,:-1]
y=df2.iloc[:,-1]
x.head()

   R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida

In [16]:
from sklearn.preprocessing import LabelEncoder
x['State']=LabelEncoder().fit_transform(x['State'])
x.head()

   R&D Spend  Administration  Marketing Spend  State
0  165349.20       136897.80        471784.10      2
1  162597.70       151377.59        443898.53      0
2  153441.51       101145.55        407934.54      1
3  144372.41       118671.85        383199.62      2
4  142107.34        91391.77        366168.42      1

In [17]:
x.corr()

                 R&D Spend  Administration  Marketing Spend     State
R&D Spend         1.000000        0.241955         0.724248  0.104685
Administration    0.241955        1.000000        -0.032154  0.011847
Marketing Spend   0.724248       -0.032154         1.000000  0.077670
State             0.104685        0.011847         0.077670  1.000000

In [18]:
from sklearn.preprocessing import Normalizer
X2=Normalizer().fit_transform(x)
X2

array([[3.19006328e-01, 2.64115366e-01, 9.10207689e-01, 3.85857721e-06],
       [3.27563005e-01, 3.04959408e-01, 8.94260721e-01, 0.00000000e+00],
       [3.42946807e-01, 2.26063621e-01, 9.11747074e-01, 2.23503279e-06],
       [3.38629722e-01, 2.78348305e-01, 8.98805948e-01, 4.69105866e-06],
       [3.52388047e-01, 2.26627050e-01, 9.07999364e-01, 2.47973150e-06],
       [3.30703621e-01, 2.50302259e-01, 9.09936203e-01, 5.01533811e-06],
       [5.68344813e-01, 6.21471815e-01, 5.39218840e-01, 0.00000000e+00],
       [3.44500729e-01, 3.84773073e-01, 8.56311234e-01, 2.64394224e-06],
       [3.29603858e-01, 4.06647710e-01, 8.52055712e-01, 5.46867377e-06],
       [3.55983080e-01, 3.13682112e-01, 8.80272446e-01, 0.00000000e+00],
       [3.71806723e-01, 4.03477489e-01, 8.36041672e-01, 3.64827285e-06],
       [3.53872252e-01, 3.22653397e-01, 8.77877676e-01, 0.00000000e+00],
       [3.17425100e-01, 4.30567545e-01, 8.44898156e-01, 3.38176453e-06],
       [3.05521274e-01, 4.50000553e-01, 8.39140187e-01, 0.00000000e+00],
       [3.70696337e-01, 4.83825142e-01, 7.92778316e-01, 3.09059799e-06],
       [3.68326257e-01, 3.94355380e-01, 8.41914249e-01, 6.43232007e-06],
       [2.58965699e-01, 4.03644906e-01, 8.77500744e-01, 0.00000000e+00],
       [2.85589428e-01, 4.37712511e-01, 8.52552894e-01, 6.03418544e-06],
       [2.78627655e-01, 3.46733775e-01, 8.95623983e-01, 3.03684148e-06],
       [4.90554488e-01, 8.71410520e-01, 0.00000000e+00, 1.13528394e-05],
       [2.32053650e-01, 3.46517836e-01, 9.08887503e-01, 0.00000000e+00],
       [2.26637153e-01, 4.44584871e-01, 8.66590961e-01, 5.78233666e-06],
       [2.20556843e-01, 3.65980630e-01, 9.04108875e-01, 2.98071700e-06],
       [2.04900173e-01, 3.20858767e-01, 9.24697556e-01, 3.03409591e-06],
       [4.08597415e-01, 5.26531510e-01, 7.45528485e-01, 1.06068574e-05],
       [3.12970038e-01, 6.75421846e-01, 6.67723809e-01, 0.00000000e+00],
       [3.57418366e-01, 6.83892464e-01, 6.36037113e-01, 4.74477271e-06],
       [1.88528584e-01, 3.34307653e-01, 9.23415056e-01, 5.22909052e-06],
       [2.90547081e-01, 8.03420336e-01, 5.19709685e-01, 4.39879478e-06],
       [3.31351277e-01, 7.72913611e-01, 5.41120025e-01, 1.01013292e-05],
       [3.88063791e-01, 7.23874021e-01, 5.70449731e-01, 6.25965071e-06],
       [3.27546662e-01, 8.18121783e-01, 4.72641442e-01, 1.07152783e-05],
       [4.19546968e-01, 8.54986126e-01, 3.04924689e-01, 0.00000000e+00],
       [2.26991380e-01, 4.21544363e-01, 8.77938075e-01, 4.09038066e-06],
       [1.73674176e-01, 5.89913418e-01, 7.88567968e-01, 0.00000000e+00],
       [2.02589266e-01, 3.74444538e-01, 9.04847433e-01, 8.80554519e-06],
       [1.19622625e-01, 5.30244370e-01, 8.39363649e-01, 4.17330542e-06],
       [2.11560290e-01, 2.46187617e-01, 9.45850887e-01, 0.00000000e+00],
       [1.02329615e-01, 3.33591847e-01, 9.37147336e-01, 1.01168254e-05],
       [1.95254761e-01, 4.20209394e-01, 8.86171340e-01, 0.00000000e+00],
       [1.35945054e-01, 5.60463387e-01, 8.16945368e-01, 0.00000000e+00],
       [1.49084251e-01, 4.52768722e-01, 8.79075862e-01, 5.34487789e-06],
       [1.32747892e-01, 5.40121331e-01, 8.31051710e-01, 0.00000000e+00],
       [1.16451677e-01, 9.56671013e-01, 2.66869969e-01, 1.50204701e-05],
       [1.39541577e-01, 9.74034909e-01, 1.78281084e-01, 0.00000000e+00],
       [8.05521927e-03, 9.99849994e-01, 1.53330470e-02, 1.61067340e-05],
       [4.12509525e-03, 3.63183143e-01, 9.31708639e-01, 3.13585761e-06],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.04752080e-02, 9.99945133e-01, 0.00000000e+00, 3.86503386e-05],
       [0.00000000e+00, 9.32865745e-01, 3.60224238e-01, 0.00000000e+00]])

In [23]:
xtrain,xtest,ytrain,ytest=train_test_split(X2,y,test_size=0.1)
print(xtrain.shape)
print(xtest.shape)

(45, 4)
(5, 4)

In [24]:
M2=LinearRegression().fit(xtrain,ytrain)
print(M2)

LinearRegression()

In [25]:
predict=M2.predict(xtest)
predict

array([ 77301.75908016, 146195.37450414, 118892.52513984,  79547.71289276,
        95072.2889789 ])

In [26]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
Mean_squared_error = mean_squared_error(ytest,predict)
print('Mean_squared_error:',Mean_squared_error)

mean_absolute_error = mean_absolute_error(ytest,predict)
print('Mean_absolute_error:',mean_absolute_error)

R_squared = r2_score(ytest,predict)
print('R_squared:',R_squared)

Mean_squared_error: 649591903.4401481
Mean_absolute_error: 20921.107512904808
R_squared: 0.7005489808993268